/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicRoutesPostsPostIdImport } from './routes/_public-routes/posts/$postId'

// Create Virtual Routes

const PublicRoutesIndexLazyImport = createFileRoute('/_public-routes/')()
const PublicRoutesTestLazyImport = createFileRoute('/_public-routes/test')()
const PublicRoutesDashboardLazyImport = createFileRoute(
  '/_public-routes/dashboard',
)()

// Create/Update Routes

const PublicRoutesIndexLazyRoute = PublicRoutesIndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_public-routes/index.lazy').then((d) => d.Route),
)

const PublicRoutesTestLazyRoute = PublicRoutesTestLazyImport.update({
  path: '/test',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_public-routes/test.lazy').then((d) => d.Route),
)

const PublicRoutesDashboardLazyRoute = PublicRoutesDashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_public-routes/dashboard.lazy').then((d) => d.Route),
)

const PublicRoutesPostsPostIdRoute = PublicRoutesPostsPostIdImport.update({
  path: '/posts/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public-routes/dashboard': {
      id: '/_public-routes/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PublicRoutesDashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/_public-routes/test': {
      id: '/_public-routes/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof PublicRoutesTestLazyImport
      parentRoute: typeof rootRoute
    }
    '/_public-routes/': {
      id: '/_public-routes/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicRoutesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_public-routes/posts/$postId': {
      id: '/_public-routes/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PublicRoutesPostsPostIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  PublicRoutesDashboardLazyRoute,
  PublicRoutesTestLazyRoute,
  PublicRoutesIndexLazyRoute,
  PublicRoutesPostsPostIdRoute,
})

/* prettier-ignore-end */
